/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_gestion_inventario;

import javax.swing.JOptionPane;

/**
 *
 * @author josep
 */
public class Principal extends javax.swing.JFrame {
    private boolean pro = true;
    private Almacen almacenPrueba;
    private Agenda agendaPrueba;
    private TMProducto modeloProductos;
    private TMProveedor modeloProveedores;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        almacenPrueba = new Almacen("C:\\datos\\objetos.dat");
        agendaPrueba = new Agenda("C:\\datos\\proveedores.dat");
        
        
        agendaPrueba.leer();
        almacenPrueba.leer();
        
        modeloProveedores = new TMProveedor(agendaPrueba.getProveedores());
        modeloProductos = new TMProducto(almacenPrueba.getProductos());
        
        tblGestion.setModel(modeloProductos);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnadir1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbSeleccionGestion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGestion = new javax.swing.JTable();
        btnAnadirGestion = new javax.swing.JButton();
        btnEliminarGestion = new javax.swing.JButton();
        btnEditarGestion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAnadirUsuarios = new javax.swing.JButton();
        btnEditarUsuarios = new javax.swing.JButton();
        btnEliminarUsuarios = new javax.swing.JButton();

        btnAnadir1.setText("Añadir");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frmPrincipal"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Bienvenido");

        jLabel2.setText("Este es una herramienta para la gestión de inventario del supermercado ABC.");

        btnSalir.setText("Salir del Programa");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(251, 251, 251))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(219, 219, 219))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Inicio", jPanel2);

        jLabel3.setText("Elementos:");

        cmbSeleccionGestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos", "Proveedores" }));
        cmbSeleccionGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSeleccionGestionActionPerformed(evt);
            }
        });

        tblGestion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0000000000", "Producto 0", "0000", "Alimentos", "Granja XXXX", "000000", "Distribucion XXXX", "Empacado en XXXX", "No"},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Categoria", "Fabricante", "Precio", "Proveedor", "Detalles envío", "Refrigerado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGestion);

        btnAnadirGestion.setText("Añadir");
        btnAnadirGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirGestionActionPerformed(evt);
            }
        });

        btnEliminarGestion.setText("Eliminar");
        btnEliminarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGestionActionPerformed(evt);
            }
        });

        btnEditarGestion.setText("Editar");
        btnEditarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarGestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSeleccionGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAnadirGestion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarGestion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarGestion)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSeleccionGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnadirGestion)
                    .addComponent(btnEliminarGestion)
                    .addComponent(btnEditarGestion))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gestión", jPanel3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btnAnadirUsuarios.setText("Añadir");
        btnAnadirUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirUsuariosActionPerformed(evt);
            }
        });

        btnEditarUsuarios.setText("Editar");

        btnEliminarUsuarios.setText("Eliminar");
        btnEliminarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAnadirUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarUsuarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarUsuarios)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnadirUsuarios)
                    .addComponent(btnEditarUsuarios)
                    .addComponent(btnEliminarUsuarios))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuarios", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSeleccionGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeleccionGestionActionPerformed
        tblGestion.setModel(modeloProductos);
        if(cmbSeleccionGestion.getSelectedIndex() == 0) {
            pro = true;
            tblGestion.setModel(modeloProductos);
        } else {
            tblGestion.setModel(modeloProveedores);
            pro = false;
        }
    }//GEN-LAST:event_cmbSeleccionGestionActionPerformed

    private void btnAnadirGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirGestionActionPerformed
        if(pro) {
        UIAnadirProducto ventanaProductos = new UIAnadirProducto(almacenPrueba, agendaPrueba);
        ventanaProductos.setLocationRelativeTo(null);
        ventanaProductos.setVisible(true);
        } else {
            UIAnadirProveedor ventanaProveedores = new UIAnadirProveedor(agendaPrueba);
            ventanaProveedores.setLocationRelativeTo(null);
            ventanaProveedores.setVisible(true);
        }
    }//GEN-LAST:event_btnAnadirGestionActionPerformed

    private void btnEliminarGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarGestionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = JOptionPane.showInternalConfirmDialog(null, "Desea Salir de la aplicación?\nLos cambios en el inventario serán guardados.", "Salir", 0);
        if(opcion == JOptionPane.YES_OPTION) {
            agendaPrueba.guardar();
            almacenPrueba.guardar();
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAnadirUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadirUsuariosActionPerformed

    private void btnEliminarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarUsuariosActionPerformed

    private void btnEditarGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarGestionActionPerformed
        int filaSeleccionada = tblGestion.getSelectedRow();
        String id = (String) tblGestion.getValueAt(filaSeleccionada, 0);
        String nombre = (String) tblGestion.getValueAt(filaSeleccionada, 1);
        String cantidad = (String) tblGestion.getValueAt(filaSeleccionada, 2);
        String categoria = (String) tblGestion.getValueAt(filaSeleccionada, 3);
        String fabricante = (String) tblGestion.getValueAt(filaSeleccionada, 4);
        String precio = (String) tblGestion.getValueAt(filaSeleccionada, 5);
        int proveedor = (Integer) tblGestion.getValueAt(filaSeleccionada, 6);
        String detalles = (String) tblGestion.getValueAt(filaSeleccionada, 7);
        boolean refrigerado = (Boolean) tblGestion.getValueAt(filaSeleccionada, 8);

        UIEditarProducto ventanaEditarProducto = new UIEditarProducto(almacenPrueba, agendaPrueba, id, nombre, cantidad, categoria, fabricante, precio, proveedor, detalles, refrigerado);
        ventanaEditarProducto.setLocationRelativeTo(null);
        ventanaEditarProducto.setVisible(true);
    }//GEN-LAST:event_btnEditarGestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir1;
    private javax.swing.JButton btnAnadirGestion;
    private javax.swing.JButton btnAnadirUsuarios;
    private javax.swing.JButton btnEditarGestion;
    private javax.swing.JButton btnEditarUsuarios;
    private javax.swing.JButton btnEliminarGestion;
    private javax.swing.JButton btnEliminarUsuarios;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbSeleccionGestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblGestion;
    // End of variables declaration//GEN-END:variables
}
